---

- name: set haproxy cfg location
  set_fact: haproxy_cfg=/etc/haproxy/haproxy.cfg

- name: install epel-release
  yum: name=epel-release state=latest
  when: ansible_distribution == 'CentOS' or haproxy_install_epel

- name: install pkg and socat for socket api
  yum: name={{ item }} state=latest
  with_items:
    - haproxy
    - socat

- name: ensure chroot directory exists
  file: name={{ haproxy_global.chroot }} state=directory
  when: haproxy_global.chroot is defined and haproxy_global.chroot

