---

- name: set haproxy cfg location
  set_fact: haproxy_cfg=/etc/haproxy/haproxy.cfg
  when: ansible_os_family == "RedHat"

- name: enable EPEL
  template: 
    src=epel.repo
    dest=/etc/yum.repos.d/epel.repo
    owner=root
    group=root
    mode=0644
  when: ansible_os_family == "RedHat"

- name: install pkg and socat for socket api
  yum: name={{ item }} state=latest
  with_items:
    - haproxy
    - socat
  when: ansible_os_family == 'RedHat'

- name: enable and start svc
  service: name=haproxy state=started enabled=yes

- name: ensure chroot directory exists
  file: name={{ haproxy_global.chroot }} state=directory
  when: haproxy_global.chroot is defined and haproxy_global.chroot

